### ISSUE TITLE
Use uint8 rather than byte

### ISSUE THREAD

**Issue by saracen** [icza/bitio#4]
I was confused for a second with `n` being of type `byte`. Using `uint8` might help to distinguish between unsigned integer vs. a byte value.

`func (r *Reader) ReadBits(n byte) (u uint64, err error)`
would become
`func (r *Reader) ReadBits(n uint8) (u uint64, err error)`

**Comment by icza** [comment]
`byte` and `uint8` are alias of each other. They are completely interchangeable. These 2 method declarations are completely equivalent:

    func (r *Reader) ReadBits(n byte) (u uint64, err error)
    func (r *Reader) ReadBits(n uint8) (u uint64, err error)

There's no point changing it. As said, they mean exactly the same.

This prints `true` (try it on the [Go Playground](https://play.golang.org/p/Nympmgw3-Hr)):

    fmt.Println(reflect.TypeOf(byte(0)) == reflect.TypeOf(uint8(0)))

**Comment by saracen** [comment]
I'm well aware byte is an alias. 

> byte is an alias for uint8 and is equivalent to uint8 in all ways. It is used, by convention, to distinguish byte values from 8-bit unsigned integer values.
https://golang.org/pkg/builtin/#byte

It's entirely up to you of course, but as I said, I think using `uint8` would help to distinguish the intent, and what is expected, purely for documentation purposes. `rune` is an alias of `int32`, they're interchangeable at a technical level, but there's still valid use cases for both.

Rob Pike previously commented this, on the proposal to remove uint8 entirely:
> The purpose of the alias is to make it clear when one is using bytes as character string elements as opposed to small integers. It adds clarity to the code and should stay.
https://github.com/golang/go/issues/22180#issuecomment-335047367

I was only confused for a second though. So it's not the end of the world :). Thank you for this library.

**Comment by icza** [comment]
Oh, I get your point now. In this sense the change does make sense. Will proceed. Thanks for the note.
