### ISSUE TITLE
GPLv2 license compatibility

### ISSUE THREAD

**Issue by Curid** [icza/bitio#6]
Apache is [incompatible](https://opensource.stackexchange.com/questions/1357/can-i-link-a-apache-2-0-library-into-software-under-gplv2) with GPLv2. Could you dual license it under GPLv2 or MIT?

**Comment by icza** [comment]
Yes, that's doable. How would I do that? Can you show me an example repo with dual license?

**Comment by Curid** [comment]
Found this.

https://github.com/sfackler/rust-postgres-macros/issues/19
https://github.com/sfackler/rust-postgres-macros/pull/20/files

**Comment by icza** [comment]
Thanks, will change to dual license soon.

**Comment by icza** [comment]
And done. Dual licensed under Apache v2 or LGPL v2.1.
