### ISSUE TITLE
Is the bit order reversed?

### ISSUE THREAD

**Issue by kaisawind** [icza/bitio#9]
```text
       H         L
       ↓         ↓ 
0x0A = 0b0000_1010
```

when `w.WriteBits(0x0A, 7)`,  get `0001_0100` .

0000_1010 << (8 - 1) = 0001_0100

```golang
package main

import (
	"bytes"
	"fmt"

	"github.com/icza/bitio"
)

func main() {
	buffer := &bytes.Buffer{}
	w := bitio.NewWriter(buffer)
	w.WriteBits(0x0A, 7)
	w.Align()
	fmt.Printf("%08b\n", 0x0A)
	fmt.Printf("%08b\n", buffer.Bytes()[0])
	fmt.Printf("%02X\n", buffer.Bytes()[0])

	// Output:
	// 00001010
	// 00010100
	// 14
}
```

**Comment by icza** [comment]
You write 7 bits, then you call `Align()`.
> Align aligns the bit stream to a byte boundary, so next write will start/go into a new byte. If there are cached bits, they are first written to the output. Returns the number of skipped (unset but still written) bits.

So in your case `Align()` will add one bit (`0`) to make the bit stream aligned to a byte boundary (multiple of 8 bits). I don't see anything wrong here. What is your expectation?

**Comment by kaisawind** [comment]
@icza 
I expect to write the low bit first when writing the bit, not the high bit.

```golang
w.WriteBits(0x0A, 7)
w.WriteBool(true)  // <-  add one bit
w.Align()
```
Expect: 1000_1010
But     :  0001_0101

**Comment by icza** [comment]
The [README.md](https://github.com/icza/bitio#bit-order) explicitly states that:

> ### Bit order
> The more general highest-bits-first order is used.

Both the reader and writer uses the highest bits first. So if you use `bitio`'s writer and reader to write and read data, you'll get the same bits.

**Comment by kaisawind** [comment]
@icza ty.
